# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

blog_list:
    path: /blog
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\BlogController::list

retrieve_event:
    path: /events/retrieve-event/{id}
    controller: App\Controller\EventController::retrieveEvent

retrieve_events:
    path: /events/retrieve-events/{group_name}
    controller: App\Controller\EventController::retrieveEvents

save_event:
    path: /events/save-event
    controller: App\Controller\EventController::saveEvent

save_attendee:
    path: /events/save-attendee
    controller: App\Controller\EventController::saveAttendee

retrieve_product:
    path: /products/retrieve-product
    controller: App\Controller\ProductController::retrieveProduct

show_action:
    path: /products/show-action
    controller: App\Controller\ProductController::showAction

save_comment:
    path: /comment/save-comment
    controller: App\Controller\CommentController::saveComment

retrieve_comment:
    path: /comment/retrieve-comments/{id}
    controller: App\Controller\CommentController::retrieveComments


retrieve_group:
    path: /group/retrieve-group/{id}
    controller: App\Controller\GroupController::retrieveGroup

retrieve_groups:
    path: /group/retrieve-groups
    controller: App\Controller\GroupController::retrieveGroups

create_group:
    path: /group/create-group
    controller: App\Controller\GroupController::createGroup

save_user:
    path: /user/save-user
    controller: App\Controller\UserController::saveUser

retrieve_user:
    path: /user/retrieve-user/{id}
    controller: App\Controller\UserController::retrieveUser


retrieve_members:
    path: /user/retrieve-members/{group_name}
    controller: App\Controller\UserController::retrieveMembers
